### PR TITLE
Update support case issue template

### PR DESCRIPTION
**Pull request by huey735**
I edited the existing template to follow the format established by
the reimbursement template and to follow some changes suggested by
@cbeams.

### CODE REVIEW

**Comment by huey735** [comment]
This was created to replace https://github.com/bisq-network/support/pull/336

**Comment by cbeams** [comment]
Thanks, @huey735. I'm happy to merge this as-is given that it's better in any case than the status quo. Would be good to get any review comments before doing so, however, if only to know that other @bisq-network/support-agents are aware of this change. I'll leave it open for a bit to allow for that.

Actually, perhaps I should just hand off merging to @leo816, who as team lead is de facto maintainer of this repository (it's not mentioned as a duty at https://bisq.wiki/Support_Team_Lead, but probably should be, and in any case, @leo816 has rights to merge changes in this repo).

**Comment by Bisq-knight** [comment]
This is a generic support issue. I thought we were aiming at having a template for DAO arbitration reimbursement requests, no?

Do we see a problem with the way bugs and standard issues are reported in the main repo (/bisq)?

Let me know if this is just the first in a series though. The template looks good for generic issues and might be a great tool for folks who do not want to go through the hassle of creating a Keybase account to share a problem

**Comment by huey735** [comment]
@Bisq-knight this is for general bug report not involving trades.

**Pull request merged**
