### PR TITLE
Add track-payments.html to report on payments to incident victims

### LINKED ISSUE #77: Implement security incident victim repayment tracking mechanism
As described in bisq-network/proposals#209:

> A mechanism will be developed to track how much BTC has been received by each address over time
[...]
> The repayment tracking mechanism mentioned above will be developed such that the USD value of each payment made to each address is calculated according to the average daily price on the day the payment was made

This means that we must implement a repayment tracking mechanism that meets the following requirements:

- tracks each utxo paid to each victim's repayment address (see https://github.com/bisq-network/admin/issues/76)
- ~~tracks the date of each payment~~ (may not be necessary to do ourselves; see https://github.com/bisq-network/admin/issues/77#issuecomment-623168964)
- tracks the USD value of the bitcoin repaid according to the btcusd average on the day of the repayment

No specific proposals have been laid out as to how to do this, but we should focus on doing the simplest thing that can possibly work in an automated fashion. This should be a fun little effort. **If you're interested in implementing this, please speak up here and lay out how you would do it.** Ideally, we should have this solution in place _before_ we merge https://github.com/bisq-network/bisq/pull/4150 and begin doing actual repayments, but given that the data is all there on the blockchain forever, we technically should be able to implement this after the fact as well. Just not _too far_ after the fact, because we should be transparent about how the repayment process is going, and because we need to remove addresses once they've been fully repaid, and this tracking mechanism is how we'll know that.

### PR DESCRIPTION
**Pull request by ghost**
The report is in HTML/pure javascript, it makes a web api call to blockchair.com to obtain the information that is presented.

Resolves bisq-network/admin#77

### CODE REVIEW

**Review by cbeams — CHANGES_REQUESTED** [review]
NACK. @jmacxx, I just made a few review commits, but am unable to push them because your PR doesn't "allow maintainers to make edits". Please check that checkbox. In the meantime, take a look at the [`track-repayments` branch](https://github.com/bisq-network/support/tree/track-repayments) I just pushed, where you'll see my changes. In particular, see commit d863a0469abcf8c5a76e78ed65aa6ab0578fa023, where I update the repayment addresses to their current values from bisq-network/admin#76. After making this change, the call to the blockchair API returns 404. Doing a bit of debugging, I narrowed it down to the following:
Notice how this call, using victim 1's original repayment address returns OK:
```
$ http head https://api.blockchair.com/bitcoin/dashboards/addresses/1EU2aUQkHQukKbk3t5fmA4quHyMRBupM2U
HTTP/1.1 200 OK
```

Whereas the same request using victim 1's new repayment address value returns 404:
```
$ http head https://api.blockchair.com/bitcoin/dashboards/addresses/13sxMq8mTw7CTSqgGiMPfwo6ZDsVYrHLmR
HTTP/1.1 404 Not Found
```

The difference between these two addresses is that the first has had transactions move through it and the latter has not. It seems that blockchair is treating the latter as "not found" for that reason, which is not what we want here. Could you look into this and see if there's a fix? Thanks.

**Comment by jmacxx** [comment]
@cbeams The box is/was already checked.  Regarding the 404 when all addresses, I'll handle it.

image

**Comment by jmacxx** [comment]
I've made a fix to handle the 404 return code when addresses are all empty.  Feel free to make your changes too, @cbeams.  I don't know why you experienced the inability to make changes, as stated earlier the box "allow edits" is and always has been checked.

**Review by cbeams — APPROVED** [review]
ACK.

> I've made a fix to handle the 404 return code when addresses are all empty.

Thanks for the fix. I've tested this locally and it works as expected for me, including when one of the addresses does have transactions.

> Feel free to make your changes too, @cbeams. I don't know why you experienced the inability to make changes, as stated earlier the box "allow edits" is and always has been checked.

My normal workflow was thrown off because you made these changes on your master branch. Not a big deal, I've now pushed my changes and will merge everything shortly. But in the future, please issue pull requests from a branch dedicated to that PR. This is especially important when you're working in a higher-traffic repository like bisq-network/bisq.

**Comment by cbeams** [comment]
And please do have a look through my review commits, @jmacxx, there are notes in the commit messages that you may find helpful in the future.

**Pull request merged**
